name: Auto Visit Serv00

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  visit_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # 使用Node.js 16版本

    - name: Install dependencies
      run: |
        npm install puppeteer

    - name: Run Puppeteer script
      run: |
        node click.js
